### ISSUE TITLE
pod 不了

### ISSUE THREAD

**Issue by wang820203420** [Pircate/RxSwiftX#1]
想要用，但是 pod 不下来

**Comment by Pircate** [comment]
@wang820203420 报什么错呢

**Comment by wang820203420** [comment]
[!] CocoaPods could not find compatible versions for pod "RxSwiftX":
  In Podfile:
    RxSwiftX

Specs satisfying the `RxSwiftX` dependency were found, but they required a higher minimum deployment target.

**Comment by Pircate** [comment]
你的工程是不是9.0以下?

**Comment by wang820203420** [comment]
对的，我支持到8.0

**Comment by Pircate** [comment]
这个只支持9.0以上，一般很少支持8.0了。

**Comment by wang820203420** [comment]
原来如此，谢谢。
